import { pkg } from '../config';
import { ModuleImports } from '../models';

//#region Add module import
export interface AddModuleImportOptions {
  imports: ModuleImports;
  importFilePath: string;
  importName: string;
  isDefaultImport?: boolean;
}
export const addModuleImport = ({
  imports,
  importFilePath,
  importName,
}: AddModuleImportOptions) => {
  if (!imports[importFilePath]) {
    imports[importFilePath] = [];
  }
  if (!imports[importFilePath].includes(importName)) {
    imports[importFilePath].push(importName);
  }
};
//#endregion

//#region get imports code
export interface GetImportsCodeOptions {
  imports?: ModuleImports;
}
export const getImportsCode = ({ imports }: GetImportsCodeOptions) => {
  if (imports) {
    return Object.keys(imports!).map((importFilePath) => {
      const importNames = imports![importFilePath];
      return `import { ${importNames.join(', ')} } from '${importFilePath}';`;
    });
  }
  return [];
};
//#endregion

//#region Get auto-generated file warning comment
export const getGeneratedFileWarningComment = () => {
  return `
    /**
     * AUTO-GENERATED FILE
     *
     * WARNING: DO NOT MODIFY THIS FILE MANUALLY
     *
     * This file has been automatically generated by the ${pkg.name} library.
     * Any manual changes made to this file will be overwritten the next time the library is run.
     * If you need to make changes to the TypeScript definitions, modify the Open API specification file
     * and regenerate the TypeScript code using the ${pkg.name} library.
     */
  `.trimIndent();
};
//#endregion
